name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - "!**_test.go"  # exclude test files to ignore unit test changes
      - "e2e/**_test.go"  # include test files in e2e again
      - ".github/workflows/e2e-tests.yaml"

env:
  GO111MODULE: on

jobs:
  test-full:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Smoke test
        working-directory: ./e2e
        run: |
          go test -v -ginkgo.v -timeout 3600s --ginkgo.label-filter=smoke

      - name: E2E test
        working-directory: ./e2e
        run: |
          go test -v -ginkgo.v -timeout 3600s --ginkgo.label-filter=e2e

      - name: Integration test
        working-directory: ./e2e
        run: |
          go test -v -ginkgo.v -timeout 3600s --ginkgo.label-filter=integration
