name: Tests

on:
  pull_request:

jobs:
  test-full:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: install goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          install-only: true

      - name: Smoke test
        working-directory: ./e2e
        run: |
          go test -v -ginkgo.v -timeout 3600s --ginkgo.label-filter=smoke

      - name: E2E test
        working-directory: ./e2e
        run: |
          go test -v -ginkgo.v -timeout 3600s --ginkgo.label-filter=e2e

      - name: Integration test
        working-directory: ./e2e
        run: |
          go test -v -ginkgo.v -timeout 3600s --ginkgo.label-filter=integration
